// Ad-hoc computed-style lift for the pharma landing archetype (replica Phase 3 step 2).
// One live navigation per width. Output: tokens-pharma-<w>.json
import { chromium } from 'playwright';
import fs from 'node:fs';
import { newLiveContext, gotoLive, dismissOverlays } from '../../scripts/diff/live-session.mjs';
const [,, url, width, out] = process.argv;
const W = Number(width);
const PROPS = ['display','position','top','zIndex','width','height','maxWidth','minWidth','marginTop','marginRight','marginBottom','marginLeft','paddingTop','paddingRight','paddingBottom','paddingLeft','fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','color','backgroundColor','backgroundImage','backgroundSize','backgroundPosition','borderTopWidth','borderBottomWidth','borderLeftWidth','borderRightWidth','borderTopColor','borderBottomColor','borderLeftColor','borderRadius','gap','columnGap','rowGap','gridTemplateColumns','flexDirection','alignItems','justifyContent','flex','alignSelf','aspectRatio','objectFit','opacity','transform','overflow','overflowX','textTransform','whiteSpace','textRendering','webkitFontSmoothing','fontVariationSettings','fontKerning','textWrap','borderTopStyle','textDecorationLine','textAlign','verticalAlign','fill','stroke'];
const SEL = {
  body:'body', page:'.tw', headerXF:'.cmp-experiencefragment--header-v3', headerbar:'.headerbar #page', contentRoot:'.container-v2.aem-GridColumn',
  crumbWrap:'.breadcrumb', crumbNav:'nav[aria-label=Breadcrumb]', crumbContainer:'nav[aria-label=Breadcrumb] .tw-container', crumbOl:'nav[aria-label=Breadcrumb] ol', crumbLi1:'nav[aria-label=Breadcrumb] ol li:nth-child(1)', crumbHome:'nav[aria-label=Breadcrumb] ol li:nth-child(1) a', crumbHomeSvg:'nav[aria-label=Breadcrumb] ol li:nth-child(1) a svg', crumbLi2:'nav[aria-label=Breadcrumb] ol li:nth-child(2)', crumbChev:'nav[aria-label=Breadcrumb] ol li:nth-child(2) > div', crumbChevSvg:'nav[aria-label=Breadcrumb] ol li:nth-child(2) > div svg', crumbA2:'nav[aria-label=Breadcrumb] ol li:nth-child(2) a', crumbA3:'nav[aria-label=Breadcrumb] ol li:nth-child(3) a',
  heroWrap:'.hero-text', heroSec:'.hero-text section', heroRow:'.hero-text section > div', heroCol:'.hero-text section > div > div > div', h1:'.hero-text h1', heroLedeWrap:'.hero-text h1 + div', heroLede:'.hero-text h1 + div > div', heroLedeP:'.hero-text h1 + div > div p',
  imgWrap:'.media-image.aem-GridColumn', imgSec:'.media-image.aem-GridColumn > section', imgInner:'.media-image.aem-GridColumn > section > div > div > div', imgPic:'.media-image.aem-GridColumn picture', img:'.media-image.aem-GridColumn picture img',
  subnavWrap:'.page-sub-nav', subnavSec:'#subnav-primary', subnavBorder:'#subnav-primary > div', subnavOuter:'.sticky-subnav-outer-container', subnavFlex:'.sticky-subnav-outer-container > div', subnavInner:'.sticky-subnav-inner-container', subnavScroll:'.subnav-primary.anchors', subnavTrack:'.js-scroll-container', subnavA1:'.js-scroll-container a:nth-child(1)', subnavA2:'.js-scroll-container a:nth-child(2)', subnavA4:'.js-scroll-container a:nth-child(4)', subnavUnderline:'.js-scroll-container a:nth-child(1) span',
  secA:'#A', secAContainer:'#A .tw-container', secARow:'#A .tw-container > div', secACol:'#A .atomic-container', secAHeadWrap:'#A .atomic-heading', secAH2:'#A h2', secARich:'#A .atomic-richtext-content', secAP1:'#A .atomic-richtext-content p:nth-child(1)', secAP2:'#A .atomic-richtext-content p:nth-child(2)',
  secB:'#B', secBContainer:'#B .tw-container', secBHead:'#B .tw-container > div:nth-child(1)', secBH2:'#B h2', secBP:'#B .tw-container > div:nth-child(1) > p', secBGrid:'#B .tw-grid', card1:'#B .tw-grid > div:nth-child(1)', card5:'#B .tw-grid > div:nth-child(5)', card7:'#B .tw-grid > div:nth-child(7)', cardMedia:'#B .tw-grid > div:nth-child(1) > div:nth-child(1)', cardMediaA:'#B .tw-grid > div:nth-child(1) > div:nth-child(1) a', cardImg:'#B .tw-grid > div:nth-child(1) img', cardBody:'#B .tw-grid > div:nth-child(1) > div:nth-child(2)', cardTitle:'#B .tw-grid > div:nth-child(1) .text-lg-bolder', cardText:'#B .tw-grid > div:nth-child(1) .atomic-richtext-content', cardTextP:'#B .tw-grid > div:nth-child(1) .atomic-richtext-content p', cardLink:'#B .tw-grid > div:nth-child(1) > div:nth-child(2) > a', cardLinkLabel:'#B .tw-grid > div:nth-child(1) > div:nth-child(2) > a > div', cardLinkSpan:'#B .tw-grid > div:nth-child(1) > div:nth-child(2) > a > div > span:nth-child(1)', cardLinkUnderline:'#B .tw-grid > div:nth-child(1) > div:nth-child(2) > a > div > span:nth-child(2)', cardLinkSvg:'#B .tw-grid > div:nth-child(1) > div:nth-child(2) > a > svg',
  secC:'#C', secCDark:'#C > div', secCContainer:'#C .tw-container', secCTrack:'#C-track', secCEyebrow:'#C-track > span', secCList:'#C-list', slide1:'#C-slide01', slide2:'#C-slide02', slideRow:'#C-slide01 > div', slideQuoteCol:'#C-slide01 > div > div:nth-child(1)', slideQuoteInner:'#C-slide01 > div > div:nth-child(1) > div', quote:'#C-slide01 p', slideMeta:'#C-slide01 > div > div:nth-child(2)', portraitWrap:'#C-slide01 > div > div:nth-child(2) > div:nth-child(1)', portrait:'#C-slide01 picture img', metaText:'#C-slide01 > div > div:nth-child(2) > div:nth-child(2)', metaName:'#C-slide01 > div > div:nth-child(2) > div:nth-child(2) span:nth-child(1)', metaRole:'#C-slide01 > div > div:nth-child(2) > div:nth-child(2) span:nth-child(2)',
  ctlWrap:'#C [data-arrows]', ctlArrows:'#C .splide__arrows', ctlPrev:'#C .splide__arrow--prev', ctlPrevSvg:'#C .splide__arrow--prev svg', ctlPrevPath:'#C .splide__arrow--prev svg path', ctlNext:'#C .splide__arrow--next', ctlNextPath:'#C .splide__arrow--next svg path', ctlPag:'#C ul.splide__pagination', ctlPagLi1:'#C ul.splide__pagination li:nth-child(1)', ctlPagB1:'#C ul.splide__pagination li:nth-child(1) button', ctlPagB2:'#C ul.splide__pagination li:nth-child(2) button', ctlPagB3:'#C ul.splide__pagination li:nth-child(3) button',
  secD:'#D', secDContainer:'#D .tw-container', secDTrack:'#D-track', secDHead:'#D-track > div:nth-child(1)', secDHeadCol:'#D-track > div:nth-child(1) > div:nth-child(1)', secDH2:'#D h2', secDList:'#D-list', dslide1:'#D-slide01', dslide2:'#D-slide02', dslide3:'#D-slide03', dMedia:'#D-slide01 > div:nth-child(1)', dImg:'#D-slide01 img', dBody:'#D-slide01 > div:nth-child(2)', dTitle:'#D-slide01 .text-lg-bolder', dText:'#D-slide01 .atomic-richtext-content', dLink:'#D-slide01 > div:nth-child(2) > a', dLinkLabel:'#D-slide01 > div:nth-child(2) > a > div',
  twoColWrap1:'.text-container-left-aligned-2-col:nth-of-type(1)', conSec:'.text-container-left-aligned-2-col section', conContainer:'.text-container-left-aligned-2-col section > .tw-container', conRow:'.text-container-left-aligned-2-col section > .tw-container > div', conCol1:'.text-container-left-aligned-2-col .atomic-container:nth-child(1)', conCol2:'.text-container-left-aligned-2-col .atomic-container:nth-child(2)', conHeadWrap:'.text-container-left-aligned-2-col .atomic-heading', conH3:'.text-container-left-aligned-2-col h3', conP:'.text-container-left-aligned-2-col .atomic-heading p',
  bannerWrap:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col', bannerSec:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col > section', bannerCol1:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(1)', bannerEmptyRich:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-child > .atomic-richtext-content', bannerMedia1:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(1) .media-image', bannerMedia1Sec:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(1) .media-image section', bannerA1:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(1) .media-image a', bannerImg1:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(1) .media-image img', bannerSpacer:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .media-image .atomic-richtext-content', bannerSpacerP:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .media-image .atomic-richtext-content p', bannerMedia2Sec:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(2) .media-image section', bannerA2:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(2) .media-image a', bannerImg2:'.text-container-left-aligned-2-col + .text-container-left-aligned-2-col .atomic-container:nth-child(2) .media-image img',
  footerXF:'.cmp-experiencefragment--footer-v3', footer:'footer#footer', fab:'#fab-component',
};
const browser = await chromium.launch();
const ctx = await newLiveContext(browser, { viewport: { width: W, height: 900 } });
const page = await ctx.newPage();
await gotoLive(page, url);
await dismissOverlays(page);
await page.waitForTimeout(1500);
await page.evaluate(() => document.fonts.ready);
const res = await page.evaluate(({ SEL, PROPS }) => {
  const out = { docH: document.documentElement.scrollHeight, vw: innerWidth, els: {} };
  for (const [k, sel] of Object.entries(SEL)) {
    const el = document.querySelector(sel);
    if (!el) { out.els[k] = null; continue; }
    const cs = getComputedStyle(el); const r = el.getBoundingClientRect();
    const o = { rect: [Math.round(r.x), Math.round(r.y + scrollY), Math.round(r.width*10)/10, Math.round(r.height*10)/10] };
    for (const p of PROPS) { const v = cs[p]; if (v !== undefined && v !== '' ) o[p] = v; }
    o.text = (el.textContent || '').trim().slice(0, 40);
    out.els[k] = o;
  }
  out.fontsLoaded = [...document.fonts].filter(f => f.status === 'loaded').map(f => f.family + ' ' + f.weight);
  out.fontsError = [...document.fonts].filter(f => f.status === 'error').map(f => f.family + ' ' + f.weight);
  return out;
}, { SEL, PROPS });
fs.writeFileSync(out, JSON.stringify(res, null, 1));
console.log('docH', res.docH, 'vw', res.vw, 'els', Object.keys(res.els).length, 'nulls', Object.entries(res.els).filter(([k,v])=>!v).map(([k])=>k).join(','), 'fontErr', res.fontsError);
await browser.close();
